version: "3.8"

services:
  app:
    build: .
    container_name: etl_app
    volumes:
      - .:/app
      - ./data:/app/data  # Mounting the data folder inside the container
    command: python main.py

