version: '3.8'

services:
  pagila_db:
    build: .
    container_name: pagila_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pagila
    ports:
      - "5432:5432"
    volumes:
      - ./dataset/pagila-dataset:/docker-entrypoint-initdb.d
      - ./export_to_csv.sh:/docker-entrypoint-initdb.d/export_to_csv.sh
      - ./csv-output:/csv-output  # Directory where CSV files will be saved
